### ISSUE TITLE
Create new "block" items for content

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#85]
The idea is to use such blocks at least in the "Getting Started" section. These blocks should help to differentiate between the possibility to self host Zammad and to subscribe to our services. My idea is to have similar blocks like on the starting page or like we already have at [Zammad.com](https://zammad.com/en/company/open-source):

![Image](https://github.com/user-attachments/assets/ffb7cc26-6b21-4175-9b32-7ef404562bfd)

![Image](https://github.com/user-attachments/assets/d1a9e7bd-1b99-4287-9bb2-c6c3e81f2834)

A two column layout should be enough. If it could be used flexible (i.e. size of box aligns automatically, depending on how many boxes/columns are used), it would be perfect, but that is no requirement.

**Comment by dvuckovic** [comment]
In the first iteration, it is now possible to include `features` section in documentation pages as well. It behaves similar to the home page features.

There are two necessary parts. First, in frontmatter YAML a structure for each `feature` has to be provided. For detailed options, take a look at the [home page features section docs](https://vitepress.dev/reference/default-theme-home-page#features-section), because this is using the same component behind it.

```yaml
features:
  - icon: 🛠️
    title: Simple and minimal, always
    details: Lorem ipsum...
    link: https://zammad.com
    linkText: This is a link
    target: _blank
  - icon:
      src: /assets/logo.svg
    title: Another cool feature
    details: Lorem ipsum...
  - icon:
      dark: /assets/logo-flat-dark.svg
      light: /assets/logo-flat-light.svg
    title: Another cool feature
    details: Lorem ipsum...
```

Second, wherever you want the features output inside the content, just include the following markup:

```vue
<VPDocFeatures />
```

Few limitations:

- Only the options listed in [the official docs](https://vitepress.dev/reference/default-theme-home-page#features-section) are currently supported. For any customizations, we would first need to fork the component and make any adjustments.
- Only one features section per page for now, but it can contain multiple items which will flow automatically.
- No markup/extra links allowed within the feature details.
